### PR TITLE
API Quickstart doc

### PR DESCRIPTION
**Pull request by jasonmadigan**
API quickstart doc.

WIP at the moment.

### CODE REVIEW

**Comment by david-martin** [comment]
@jasonmadigan 
Trying this out locally, it doesn't like the private repo:

```
mkdocs_multirepo_plugin.util.BashException:
Cloning into 'api-quickstart'...
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/kuadrant/api-quickstart/'
```

Should we move the repo to public, or switch to an ssh url so key auth is used?

**Comment by jasonmadigan** [comment]
@david-martin this should work locally now.

**Comment by david-martin** [comment]
The wiring up works locally.
The document looks to render correctly, though I haven't gone through it fully.
Once this is merged, is there an extra step to deploy, or is the README from main of api-quickstart deployed there and then?
Should we hold off merge until the current round of testing and updates finish?

**Comment by jasonmadigan** [comment]
@david-martin yes I think this should remain on hold until other PRs and cherry picks land

**Comment by jasonmadigan** [comment]
@R-Lawton @david-martin merged

**Pull request merged**
