### PR TITLE
Use main ref until next release to simplify testing

### PR DESCRIPTION
**Pull request by david-martin**
Latest docs changes have not been tested with older 0.6.1 release.
This change will ease the transition to the upcoming release.

### CODE REVIEW

**Comment by pehala** [comment]
This is simply wrong, published Docs cannot use main. If we are publishing docs that dont work on already released releases we have a fundemental problem with how we deal with docs and this is not a solution

**Comment by david-martin** [comment]
Thanks for the insight @pehala. I see where you are coming from.

This isn't ideal, but I think it's pragmatic given we don't have a staging docs site at this time, or a release process for the docs site geared at a big bang. Merging this change will make the latest docs that are already published much more likely to work.

There's an unresolved question in the release process proposal [here](https://github.com/Kuadrant/architecture/pull/41/files#diff-eeceecbdf5c1a6fc2cc490b55dd4351651d64c8a740458325511493e52f7616aR825) around docs.
I don't think we're going to solve this quickly.
I also don't think we should halt the release to iron out this process right now, but instead capture the pain points and gaps so we can improve it for next release.

If you have other suggestions too on how to progress, please do share.

**Comment by jasonmadigan** [comment]
> This is simply wrong, 

I don’t think this is as clear cut. While I can understand and appreciate the need for stability in documentation that aligns with released versions for downstream, I would contend that our upstream environment operates differently (and should operate differently). I would contend that upstream should lean into flexibility, pace and continuous evolution.

> published Docs cannot use main

I disagree. Our other upstream components move along on main quickly, I believe our docs should move at a similar pace upstream. Pushing docs quickly in my view aids the facilitation of early testing and feedback: by documenting features as they are developed, we can gather early feedback earlier, rather than gathering docs into larger blobs. I'm a proponent of a fast moving `main` for all components upstream, and that includes docs.

> If we are publishing docs that dont work on already released releases we have a fundemental problem with how we deal with docs and this is not a solution

> Edit: We can do this on a staging, if we had any but for a doc that goes immediately public this is unnacceptable

I think this needs to be discussed on our community call or ML, as I don't believe this is a consensus view.

I would concede that our docs could do with multi-versioning, so stable content can be accessed alongside content that tracks to a particular release. e.g. a picker for `0.6.1 `docs vs `latest`. I don't believe there is anything inherently wrong with a latest version of the docs tracking `main` of components.

**Comment by pehala** [comment]
> This isn't ideal, but I think it's pragmatic given we don't have a staging docs site at this time, or a release process for the docs site geared at a big bang. Merging this change will make the latest docs that are already published much more likely to work.

If the latest docs that are published do not work on previous version, that is the core issue we need to solve, not that it is pointing to a released version

> I also don't think we should halt the release to iron out this process right now, but instead capture the pain points and gaps so we can improve it for next release.

Agree, but this change is not required for anything. It is fairly easy for people doing the testing to replace the tag with the correct one (not to mention `main` is wrong tag for this, we should be using `0.7.0-rc2` for testing) and it is definitely not needed.





> I don’t think this is as clear cut. While I can understand and appreciate the need for stability in documentation that aligns with released versions for downstream, I would contend that our upstream environment operates differently (and should operate differently). I would contend that upstream should lean into flexibility, pace and continuous evolution.

It should not I believe stable and working docs are necessary even for upstream. This is the ONLY place we have to new users to come and try it out (at ANY time no matter when we release), if they find out that half of the docs are wrong they wont have much enthusiasm to continue trying it out, especially with a project that did not yet break out. Docs are aimed at potential users who want to get up and running as quickly as possible with the stable release, without having to deal with unnecessary bugs introduced by having everything at main, which will likely be broken a lot, especially since docs move way slower than code changes.



> I disagree. Our other upstream components move along on main quickly, I believe our docs should move at a similar pace upstream. Pushing docs quickly in my view aids the facilitation of early testing and feedback: by documenting features as they are developed, we can gather early feedback earlier, rather than gathering docs into larger blobs. I'm a proponent of a fast moving `main` for all components upstream, and that includes docs.
> 
They should move quickly and be updated but what you are suggesting is testing on production. If you want to update docs or add new ones to existing release feel free to backport the changes, if the doc does not work with previous release it should never make it way to docs.kuadrant.io site until it is released.

One of the ways how to achieve is to create staging docs, where I fully agree keep everything on main, but staging currently does not exist and doing this on production seems inherently wrong.





> I think this needs to be discussed on our community call or ML, as I don't believe this is a consensus view.

Agreed, until then I would keep it as it is now (so do not merge this PR) and keep this status quo, as I believe it doesnt block anything.

**Comment by jasonmadigan** [comment]
This'll flow to the 0.7.0 dev release now, so safe to merge

the 0.6.1 will continue to refer to the 0.6.1 release.

when 0.7.0 is stable, we'll ship those docs as a stable version and update the KUADRANT_REF to 0.7.0

At some point, we'll automate all of this stuff.

**Pull request merged**
