### PR TITLE
re-add dns-provider guide

### PR DESCRIPTION
**Pull request by jasonmadigan**
https://deploy-preview-112--graceful-kangaroo-3c9c10.netlify.app/dns-operator/docs/provider/

### CODE REVIEW

**Comment by david-martin** [comment]
👀

**Comment by david-martin** [comment]
Were there any recent changes to the doc page in particular?

Noticed a url that doesn't render as a link. I think it's because of a missing newline before it?

image

**Comment by jasonmadigan** [comment]
@netlify /rebuild

**Comment by jasonmadigan** [comment]
@netlify /rerun

**Comment by jasonmadigan** [comment]
Hmm, odd. Usually single-line links are transformed into hyperlinks, but not so:

https://deploy-preview-112--graceful-kangaroo-3c9c10.netlify.app/dns-operator/docs/provider/

**Comment by david-martin** [comment]
I think they'll have to be markdown formatted links.
I tested locally with this and it renders ok

```markdown
[https://cloud.google.com/dns/docs/access-control#dns.admin](https://cloud.google.com/dns/docs/access-control#dns.admin)
```

**Comment by jasonmadigan** [comment]
Have patched in https://github.com/Kuadrant/dns-operator/pull/154

**Comment by jasonmadigan** [comment]
OK, sorted: https://deploy-preview-112--graceful-kangaroo-3c9c10.netlify.app/dns-operator/docs/provider/

@david-martin ^

**Pull request merged**
